const char* test = "\n"
"local redraw = true;\n"
"local cursor = {x = 1, y = 1};\n"
"local canvas = \n"
"{\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"    {32,32,32,32,32,32},\n"
"};\n"
"local x = 1;\n"
"local y = 1;\n"
"\n"
"function buttonDown(button)\n"
"    return digitalRead(button) == HIGH;\n"
"end\n"
"\n"
"function drawBoard()\n"
"    for x = 0, 15 do\n"
"        for y = 0, 5 do\n"
"            if (cursor.x == x+1 and cursor.y == y+1) then\n"
"                oled_setColor(WHITE);\n"
"                oled_fillRect(x * 8, y * 8, 8, 8);\n"
"                oled_setColor(BLACK);\n"
"            end\n"
"            oled_drawString(x * 8, y * 8, string.char(canvas[x+1][y+1]));\n"
"            oled_setColor(WHITE);\n"
"        end\n"
"    end\n"
"end\n"
"function move()\n"
"    if buttonDown(BTN_1) then\n"
"        if buttonDown(BTN_2) then\n"
"            if buttonDown(BTN_4) then\n"
"                if cursor.y > 1 then\n"
"                    cursor.y = cursor.y - 1\n"
"                else\n"
"                    cursor.y = 6\n"
"                end\n"
"                redraw = true\n"
"            elseif buttonDown(BTN_5) then\n"
"                if cursor.y < 6 then\n"
"                    cursor.y = cursor.y + 1\n"
"                else\n"
"                    cursor.y = 1\n"
"                end\n"
"                redraw = true\n"
"            end\n"
"        elseif buttonDown(BTN_4) then\n"
"            if cursor.x > 1 then\n"
"                cursor.x = cursor.x - 1\n"
"            else\n"
"                if cursor.y > 1 then\n"
"                    cursor.y = cursor.y - 1\n"
"                    cursor.x = 16\n"
"                else\n"
"                    cursor.y = 6\n"
"                    cursor.x = 16\n"
"                end\n"
"            end\n"
"            redraw = true\n"
"        elseif buttonDown(BTN_5) then\n"
"            if cursor.x < 16 then\n"
"                cursor.x = cursor.x + 1\n"
"            else\n"
"                if cursor.y < 6 then\n"
"                    cursor.y = cursor.y + 1\n"
"                    cursor.x = 1\n"
"                else\n"
"                    cursor.y = 1\n"
"                    cursor.x = 1\n"
"                end\n"
"            end\n"
"            redraw = true\n"
"        end\n"
"    elseif buttonDown(BTN_5) then\n"
"        if canvas[cursor.x][cursor.y] < 255 then\n"
"            canvas[cursor.x][cursor.y] = canvas[cursor.x][cursor.y] + 1\n"
"        else\n"
"            canvas[cursor.x][cursor.y] = 0\n"
"        end\n"
"        redraw = true\n"
"    elseif buttonDown(BTN_4) then\n"
"        if canvas[cursor.x][cursor.y] > 0 then\n"
"            canvas[cursor.x][cursor.y] = canvas[cursor.x][cursor.y] - 1\n"
"        else\n"
"            canvas[cursor.x][cursor.y] = 255\n"
"        end\n"
"        redraw = true\n"
"    end\n"
"end\n"
"oled_init();\n"
"function loop()\n"
"    move();\n"
"    if redraw == true then\n"
"        oled_clear();\n"
"        oled_setColor(WHITE);\n"
"        oled_drawString(0, 56, canvas[cursor.x][cursor.y] .. \"\");\n"
"        oled_drawLine(0, 54, 127, 54);\n"
"        drawBoard();\n"
"        oled_display();\n"
"        redraw = false;\n"
"    end\n"
"    delay(10);\n"
"end\n"
"\n";